#!/usr/bin/env python3
"""Build the full top-chart app-category mapping from parsed chart rows."""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "research" / "data"


FREE_TOP = [
    (1, "WhatsApp Messenger", "Get", "Social Networking"),
    (2, "Amazon Prime Video", "Get", "Entertainment"),
    (3, "Microsoft Word", "Get", "Productivity"),
    (4, "Microsoft Outlook", "Get", "Productivity"),
    (5, "Microsoft Excel", "Get", "Productivity"),
    (6, "CapCut: Photo & Video Editor", "Get", "Photo & Video"),
    (7, "Canva: AI Video & Photo Editor", "Get", "Photo & Video"),
    (8, "Microsoft PowerPoint", "Get", "Productivity"),
    (9, "WidgetWall", "Get", "Productivity"),
    (10, "Save to Pinterest", "Get", "Lifestyle"),
    (11, "HP: Print and Support", "Get", "Productivity"),
    (12, "Slack for Desktop", "Get", "Business"),
    (13, "Telegram", "Get", "Social Networking"),
    (14, "Amazon Kindle: Reading App", "Get", "Books"),
    (15, "Join for Zoom Meetings", "Get", "Productivity"),
    (16, "Apps for Google App", "Get", "Productivity"),
    (17, "Xcode", "Get", "Developer Tools"),
    (18, "Capital One Shopping Extension", "Get", "Shopping"),
    (19, "Windows App", "Get", "Business"),
    (20, "NordVPN: VPN Fast & Secure", "Get", "Utilities"),
    (21, "Mail for Gmail", "Get", "Productivity"),
    (22, "OneDrive", "Get", "Productivity"),
    (23, "Color Widgets", "Get", "Utilities"),
    (24, "DuckDuckGo, optional Duck.ai", "Get", "Utilities"),
    (25, "PDFgear: PDF Editor & Reader", "Get", "Business"),
    (26, "Microsoft Copilot", "Get", "Productivity"),
    (27, "AI ChatbotㆍAsk AI Anything 5.4", "Get", "Education"),
    (28, "App for Youtube!", "Get", "Utilities"),
    (29, "Okta Verify", "Get", "Business"),
    (30, "Adobe Lightroom: Photo Editor", "Get", "Photo & Video"),
    (31, "Open Link Pro - Browser Picker", "Get", "Business"),
    (32, "Widgetter - Custom Desktop", "Get", "Utilities"),
    (33, "The Unarchiver", "Get", "Utilities"),
    (34, "WeChat", "Get", "Social Networking"),
    (35, "Docs for Google Docs and Drive", "Get", "Productivity"),
    (36, "Join for Teams", "Get", "Productivity"),
    (37, "VPN: Super Unlimited, Fast VPN", "Get", "Utilities"),
    (38, "TestFlight", "Get", "Developer Tools"),
    (39, "Goodnotes: AI Notes, Docs, PDF", "Get", "Productivity"),
    (40, "Streaming for Netflix", "Get", "Entertainment"),
    (41, "DaVinci Resolve", "Get", "Photo & Video"),
    (42, "Grammarly: AI Writing App", "Get", "Productivity"),
    (43, "Apple Developer", "Get", "Developer Tools"),
    (44, "Final Cut Pro: Create Video", "Get", "Photo & Video"),
    (45, "C.AI: AI Chatbot Assistant", "Get", "Productivity"),
    (46, "Unzip - RAR ZIP 7Z Unarchiver", "Get", "Utilities"),
    (47, "Mail+ for Gmail", "Get", "Productivity"),
    (48, "Silicio: Widgets + Mini Player", "Get", "Music"),
    (49, "uBlock Origin Lite", "Get", "Utilities"),
    (50, "AI Chatbot - Ask AI Anything‎", "Get", "Productivity"),
    (51, "WPS Office: AI Doc, PDF, Sheet", "Get", "Business"),
    (52, "Microsoft OneNote", "Get", "Productivity"),
    (53, "Calendar for Google Calendar‎", "Get", "Productivity"),
    (54, "Brother iPrint&Scan", "Get", "Utilities"),
    (55, "Chatbot: Ask Chat AI Assistant", "Get", "Education"),
    (56, "PDF Reader: PDF Editor,Convert", "Get", "Productivity"),
    (57, "ExpressVPN · Secure & Fast VPN", "Get", "Utilities"),
    (58, "Streaming Player for Peacock", "Get", "Entertainment"),
    (59, "Join for Zoom", "Get", "Productivity"),
    (60, "Amphetamine", "Get", "Utilities"),
    (61, "Logic Pro: Make Music", "Get", "Music"),
    (62, "Happ - Proxy Utility", "Get", "Utilities"),
    (63, "Bluebook Exams", "Get", "Education"),
    (64, "Free VPN by Free VPN .org™", "Get", "Utilities"),
    (65, "VinylPod - Music Widget", "Get", "Music"),
    (66, "App for YouTube ℠", "Get", "Productivity"),
    (67, "Teleparty - Watch TV Together", "Get", "Entertainment"),
    (68, "NotchBox - Easier Drag & Drop", "Get", "Productivity"),
    (69, "VPN cat: Fast Secure Unlimited", "Get", "Utilities"),
    (70, "Apple Configurator", "Get", "Utilities"),
    (71, "VPN Proxy Maste® Unlimited VPN", "Get", "Utilities"),
    (72, "CleanMyMac", "Get", "Utilities"),
    (73, "Tailscale", "Get", "Utilities"),
    (74, "Surfshark VPN: stable & fast", "Get", "Utilities"),
    (75, "App for Facebook Messenger", "Get", "Social Networking"),
    (76, "App for TikTok", "Get", "Social Networking"),
    (77, "App for Google Search ®‎", "Get", "Productivity"),
    (78, "Notability: AI Notes & PDF app", "Get", "Productivity"),
    (79, "Friendly Streaming Browser", "Get", "Entertainment"),
    (80, "iWallpaper - Live Wallpaper", "Get", "Utilities"),
    (81, "App for Zoom Meetings °", "Get", "Productivity"),
    (82, "Spreadsheet-xlsx&csv editor", "Get", "Productivity"),
    (83, "WireGuard", "Get", "Utilities"),
    (84, "djay - DJ App & AI Mixer", "Get", "Music"),
    (85, "App for YouTube •", "Get", "Lifestyle"),
    (86, "Openly a Link - Browser Picker", "Get", "Productivity"),
    (87, "MKPlayer - MKV & Media Player", "Get", "Photo & Video"),
    (88, "Pixelmator Pro: Edit Images", "Get", "Graphics & Design"),
    (89, "App For Team Meetings", "Get", "Social Networking"),
    (90, "Open App for All Browser", "Get", "Productivity"),
    (91, "App for Gmail ®", "Get", "Productivity"),
    (92, "Meeting for Teams ®", "Get", "Productivity"),
    (93, "Streaming Master", "Get", "Lifestyle"),
    (94, "HP Smart Printer App & Scanner", "Get", "Business"),
    (95, "OP Auto Clicker", "Get", "Utilities"),
    (96, "Parallels Desktop", "Get", "Business"),
    (97, "Notion Web Clipper", "Get", "Productivity"),
    (98, "MacDroid - Manager for Android", "Get", "Utilities"),
]


PAID_OVERALL_TOP = [
    (1, "Shadowrocket", "£2.99"),
    (2, "Logic Pro", "£199.99"),
    (3, "TV Launcher - Live UK Channels", "£5.99"),
    (4, "DaisyDisk", "£9.99"),
    (5, "Wipr 2", "£4.99"),
    (6, "RAR Extractor - Unarchiver Pro", "£3.99"),
    (7, "MediaInfo", "£0.99"),
    (8, "Things 3", "Open/Purchased"),
    (9, "UTM Virtual Machines", "£9.99"),
    (10, "IPTV Smart Pro - 4K Live TV", "£4.99"),
    (11, "PDF Expert - Edit, Sign PDFs", "£129.99"),
    (12, "Pixelmator Pro", "£49.99"),
    (13, "Final Cut Pro", "£299.99"),
    (14, "Mp3tag", "£24.99"),
    (15, "forScore", "£24.99"),
    (16, "BetterSnapTool", "£1.99"),
    (17, "Parall", "£9.99"),
    (18, "Minimoog Model D Synthesizer", "£14.99"),
    (19, "DeskMat - Cover your Desktop", "£3.99"),
    (20, "Keka", "£5.99"),
    (21, "GrandPerspective", "£2.99"),
    (22, "PhotoSweeper", "£14.99"),
    (23, "MacFamilyTree 11", "£69.99"),
    (24, "Parachute Backup", "£14.99"),
    (25, "Magnet", "Open"),
    (26, "SponsorBlock for Safari", "£2.99"),
    (27, "Iris: Photo & Video Library", "£14.00"),
    (28, "Vinegar - Tube Cleaner", "£1.99"),
    (29, "Logoist 6 - Graphic Design", "£19.99"),
    (30, "Moom Classic", "£6.99"),
    (31, "LibreOffice", "£8.99"),
    (32, "LosslessCut", "£19.99"),
    (33, "Upscayl", "£12.99"),
    (34, "SiteSucker", "£5.99"),
    (35, "Scrivener 3", "£59.99"),
    (36, "TextSniper", "£9.99"),
    (37, "SimpleMind Pro", "£29.99"),
    (38, "PixelStyle Photo Editor", "£5.99"),
    (39, "Dynamic DNS client - RealDNS", "£4.99"),
    (40, "MainStage", "£29.99"),
    (41, "Starry Landscape Stacker", "£39.99"),
    (42, "Quantumult X", "£9.99"),
    (43, "IP Scanner Ultra", "£49.99"),
    (44, "Short Run", "£6.00"),
    (45, "BRAW Toolbox", "£79.99"),
    (46, "Msg Converter Pro", "£5.99"),
    (47, "Offline Files", "£8.99"),
    (48, "pwSafe - Password Safe", "£14.99"),
    (49, "Tune Sweeper", "£22.99"),
    (50, "Command X", "£4.00"),
    (51, "PDF Reader Pro - Edit&Convert", "£79.99"),
    (52, "Smart Converter Pro 3", "£14.99"),
    (53, "Dark Night - mode for Safari", "£0.99"),
    (54, "Gyroflow Toolbox", "£9.99"),
    (55, "Screen Shade", "£1.99"),
    (56, "Color Folder Master", "£1.99"),
    (57, "ChatShare for WhatsApp", "£3.99"),
    (58, "TouchDraw 2: Draw and Diagram", "£24.99"),
    (59, "Focus & ADHD Reading - Glide", "£6.99"),
    (60, "md - Markdown writing App", "£0.99"),
    (61, "Patterning 3: Drum Machine", "£29.99"),
    (62, "Mouse Coordinates", "£0.99"),
    (63, "Icon Composer", "£0.99"),
    (64, "AirSpace: Manage Desktop Spaces", "£9.99"),
    (65, "captionTranslator", "£34.99"),
    (66, "MenuBarPad", "£1.99"),
    (67, "Basic PDF Reader", "£1.99"),
    (68, "3D Video Meta Data injector", "£4.99"),
    (69, "Webmail App", "£2.99"),
    (70, "Inset: Preview Any Screen Area", "£3.99"),
    (71, "Noir - Dark Mode for Safari", "£3.99"),
    (72, "Dark Reader for Safari", "£4.99"),
    (73, "Paperman: Your screen as paper", "£5.99"),
    (74, "Jump Desktop (RDP, VNC, Fluid)", "£34.99"),
    (75, "Klack", "£4.99"),
    (76, "iA Writer", "£49.99"),
    (77, "Tampermonkey", "£2.99"),
    (78, "Velja", "£8.00"),
    (79, "Shutter Counter", "£0.99"),
    (80, "ShutterCount", "£8.99"),
    (81, "Phiewer PRO", "£7.99"),
    (82, "Meta - Music Tag Editor", "£22.99"),
    (83, "Create Booklet 2", "£19.99"),
    (84, "Sketchbook Pro", "£24.99"),
    (85, "miRack", "£14.99"),
    (86, "Node.js/JavaScript Compiler", "£0.99"),
    (87, "App Trust Preview", "£4.99"),
    (88, "Paranoia File Encryption PRO", "£3.99"),
    (89, "LinkMyDroid", "£14.99"),
    (90, "iReal Pro", "£19.99"),
    (91, "GraphicConverter 12", "£39.99"),
    (92, "Disk Drill Data Recovery", "£89.99"),
    (93, "Motion", "£49.99"),
    (94, "iStat Menus 7", "£11.99"),
    (95, "Final Draft 13", "£199.99"),
    (96, "RailModeller Pro", "£44.99"),
    (97, "AltTab Switcher", "£2.99"),
    (98, "Folder Tidy", "£4.99"),
    (99, "Whisper Notes - Speech to Text", "£6.99"),
    (100, "Webcam Settings", "£7.99"),
]


PAID_PRODUCTIVITY_TOP = [
    (1, "Things 3"),
    (2, "PDF Expert - Edit, Sign PDFs"),
    (3, "BetterSnapTool"),
    (4, "Parall"),
    (5, "MacFamilyTree 11"),
    (6, "Magnet"),
    (7, "SponsorBlock for Safari"),
    (8, "LibreOffice"),
    (9, "LosslessCut"),
    (10, "Scrivener 3"),
    (11, "TextSniper"),
    (12, "SimpleMind Pro"),
    (13, "Short Run"),
    (14, "Msg Converter Pro"),
    (15, "Offline Files"),
    (16, "PDF Reader Pro - Edit&Convert"),
    (17, "md - Markdown writing App"),
    (18, "Webmail App"),
    (19, "Dark Reader for Safari"),
    (20, "iA Writer"),
    (21, "Tampermonkey"),
    (22, "Final Draft 13"),
    (23, "AltTab Switcher"),
    (24, "Whisper Notes - Speech to Text"),
    (25, "HazeOver - Distraction Dimmer"),
    (26, "NotchPrompter"),
    (27, "Tampermonkey Classic"),
    (28, "xSearch for Safari"),
    (29, "nvEnvy"),
    (30, "Maccy"),
    (31, "Greenshot"),
    (32, "ReminderBridge"),
    (33, "Unclutter"),
    (34, "TaskControl for Asana"),
    (35, "MarkDownload"),
    (36, "MailTrackerBlocker for Mail"),
    (37, "Hide Mouse Cursor"),
    (38, "Narrativ Timeline"),
    (39, "iA Presenter"),
    (40, "Glance - Prevent Eye Strain"),
    (41, "Redacto"),
    (42, "Count Down: Menu Bar Timer"),
    (43, "Histogrammer"),
    (44, "Quit All Apps"),
    (45, "Trace: On-Device Transcripts"),
    (46, "Clicker - Presentation Remote"),
    (47, "UnTrap for YouTube"),
    (48, "FileBrowser Pro"),
    (49, "Presentify - Screen Annotation"),
    (50, "Password Manager Data Vault"),
    (51, "Quiver - take better notes"),
    (52, "GoodTask"),
    (53, "PDF Professional Suite"),
    (54, "Scrap Paper"),
    (55, "AI Overview Hider for Google"),
    (56, "FolderToList"),
    (57, "Day Progress"),
    (58, "SideNotes & Workspaces"),
    (59, "PreviewMarkdown"),
    (60, "Show StopWatch"),
    (61, "PlainPad"),
    (62, "PST Viewer - Email Reader"),
    (63, "iWriter 2"),
    (64, "PDF Merge & Split - PageForge"),
    (65, "CCCCorners"),
    (66, "CopyClip 2 - Clipboard Manager"),
    (67, "GCal for Google Calendar"),
    (68, "Scratchpad"),
    (69, "Cursor Pro"),
    (70, "Theine"),
    (71, "Timeless: Alarm Clock"),
    (72, "Gestimer 2"),
    (73, "Lock Pro"),
    (74, "Collective AI"),
    (75, "TabPilot"),
    (76, "Outliner"),
    (77, "Cyberduck"),
    (78, "Aiko"),
    (79, "AudioNote-Note+Voice Recorder"),
    (80, "Be Focused Pro: Pomodoro Timer"),
    (81, "Byword"),
    (82, "OmmWriter"),
    (83, "PDFScanner - Scanning and OCR"),
    (84, "Scapple"),
    (85, "eWallet"),
    (86, "Unibox"),
    (87, "Instashare - Transfer files"),
    (88, "PDF Toolkit +"),
    (89, "PDF to Word +"),
    (90, "MailRaider"),
    (91, "To-do Lists"),
    (92, "Gestimer (Legacy)"),
    (93, "The Clock"),
    (94, "eXtra Voice Recorder Pro."),
    (95, "WriteRoom"),
    (96, "iCircuit"),
    (97, "Due - Reminders & Timers"),
    (98, "Project Planner - Gantt app"),
    (99, "Ad Auto-Skipper for YouTube"),
    (100, "Split Screen"),
]


PRODUCTIVITY_PRICE_OVERRIDES = {
    "HazeOver - Distraction Dimmer": "£4.99",
    "NotchPrompter": "£4.99",
    "Tampermonkey Classic": "£1.99",
    "xSearch for Safari": "£2.99",
    "nvEnvy": "£1.99",
    "Maccy": "£9.99",
    "Greenshot": "£1.99",
    "ReminderBridge": "£7.99",
    "Unclutter": "£19.99",
    "TaskControl for Asana": "£7.99",
    "MarkDownload": "£2.99",
    "MailTrackerBlocker for Mail": "£6.99",
    "Hide Mouse Cursor": "£0.99",
    "Narrativ Timeline": "£9.99",
    "iA Presenter": "£64.00",
    "Glance - Prevent Eye Strain": "£0.99",
    "Redacto": "£4.99",
    "Count Down: Menu Bar Timer": "£2.99",
    "Histogrammer": "£4.99",
    "Quit All Apps": "£1.99",
    "Trace: On-Device Transcripts": "£9.99",
    "Clicker - Presentation Remote": "£4.99",
    "UnTrap for YouTube": "£3.99",
    "FileBrowser Pro": "£14.99",
    "Presentify - Screen Annotation": "£14.99",
    "Password Manager Data Vault": "£9.99",
    "Quiver - take better notes": "£9.99",
    "GoodTask": "£39.99",
    "PDF Professional Suite": "£29.99",
    "Scrap Paper": "£1.99",
    "AI Overview Hider for Google": "£0.99",
    "FolderToList": "£0.99",
    "Day Progress": "£4.00",
    "SideNotes & Workspaces": "View",
    "PreviewMarkdown": "£2.99",
    "Show StopWatch": "£3.99",
    "PlainPad": "£1.99",
    "PST Viewer - Email Reader": "£7.99",
    "iWriter 2": "£14.99",
    "PDF Merge & Split - PageForge": "£6.99",
    "CCCCorners": "£2.99",
    "CopyClip 2 - Clipboard Manager": "£7.99",
    "GCal for Google Calendar": "£4.99",
    "Scratchpad": "£10.00",
    "Cursor Pro": "£17.99",
    "Theine": "£3.99",
    "Timeless: Alarm Clock": "£4.99",
    "Gestimer 2": "£6.99",
    "Lock Pro": "£5.99",
    "Collective AI": "£2.99",
    "TabPilot": "£3.99",
    "Outliner": "£4.99",
    "Cyberduck": "£22.99",
    "Aiko": "£25.00",
    "AudioNote-Note+Voice Recorder": "£14.99",
    "Be Focused Pro: Pomodoro Timer": "£14.99",
    "Byword": "£9.99",
    "OmmWriter": "£9.99",
    "PDFScanner - Scanning and OCR": "£24.99",
    "Scapple": "£19.99",
    "eWallet": "£19.99",
    "Unibox": "£12.99",
    "Instashare - Transfer files": "£4.99",
    "PDF Toolkit +": "£1.99",
    "PDF to Word +": "£6.99",
    "MailRaider": "£3.99",
    "To-do Lists": "£4.99",
    "Gestimer (Legacy)": "£6.99",
    "The Clock": "£4.99",
    "eXtra Voice Recorder Pro.": "£4.99",
    "WriteRoom": "£4.99",
    "iCircuit": "£12.99",
    "Due - Reminders & Timers": "£14.99",
    "Project Planner - Gantt app": "£9.99",
    "Ad Auto-Skipper for YouTube": "£0.99",
    "Split Screen": "£2.99",
}


@dataclass(frozen=True)
class Category:
    label: str
    replaceability: str
    skill_fit: str
    reason: str


@dataclass(frozen=True)
class AgentReadiness:
    level: str
    basis: str
    evidence_key: str


CATEGORY_META = {
    "storage_audit": Category(
        "storage_audit",
        "yes",
        "macos-system-data-audit",
        "Core job is local disk inspection and reporting; deletion remains approval-gated.",
    ),
    "archive_tools": Category(
        "archive_tools",
        "yes",
        "archive-batch-tools",
        "Archive listing, extraction, and batch validation are deterministic file workflows.",
    ),
    "pdf_document_tools": Category(
        "pdf_document_tools",
        "partial",
        "pdf-file-audit / pdf",
        "Batch inspection, split/merge/OCR/reporting can be skills; rich visual editing/signing remains app work.",
    ),
    "image_media_batch": Category(
        "image_media_batch",
        "partial",
        "image-batch-convert / candidate media-metadata-audit",
        "Batch conversion, metadata, contact sheets, and audits fit skills; interactive editing remains app work.",
    ),
    "video_media_batch": Category(
        "video_media_batch",
        "partial",
        "candidate video-batch-utility",
        "Transcode, trim, metadata, captions, and reports fit ffmpeg-style skills; timeline editing does not.",
    ),
    "browser_extension_or_web_wrapper": Category(
        "browser_extension_or_web_wrapper",
        "partial",
        "browser-shell-audit / playwright",
        "Agents can replace wrapper workflows, shortcuts, and reports; live browser extensions still need an app or extension.",
    ),
    "office_documents": Category(
        "office_documents",
        "partial",
        "documents / spreadsheets / presentations",
        "Creation, conversion, review, and cleanup fit agent workflows; full interactive office UI does not.",
    ),
    "email_calendar_meetings": Category(
        "email_calendar_meetings",
        "partial",
        "gmail / calendar-meeting-audit",
        "Search, triage, drafting, exports, and meeting notes fit connectors; the live client/service remains.",
    ),
    "ai_chat_or_writing": Category(
        "ai_chat_or_writing",
        "partial",
        "Codex/Claude writing workflows",
        "General writing and chat overlap with agents; app-specific accounts, communities, and integrations may not.",
    ),
    "developer_tools": Category(
        "developer_tools",
        "partial",
        "Codex repo automation / developer-cache-audit",
        "Code generation, audits, and repo maintenance fit agents; IDE/runtime/distribution surfaces remain.",
    ),
    "system_utility": Category(
        "system_utility",
        "partial",
        "launch-agent-audit / plist-defaults-audit / shell scripts",
        "Inspection and config reporting fit skills; resident menu-bar, input, and always-on behavior usually remains an app.",
    ),
    "window_workspace_management": Category(
        "window_workspace_management",
        "no",
        "none",
        "Value is real-time resident window control, not an offline agent workflow.",
    ),
    "backup_sync_storage_service": Category(
        "backup_sync_storage_service",
        "partial",
        "backup-audit",
        "Backup verification and inventory fit skills; sync engines and cloud clients remain services.",
    ),
    "network_security": Category(
        "network_security",
        "no",
        "none",
        "VPN/proxy/MFA/network clients depend on live networking, trust, and OS integration.",
    ),
    "messaging_social": Category(
        "messaging_social",
        "no",
        "none",
        "Network effects, accounts, push notifications, and encrypted client UX are the product.",
    ),
    "streaming_content": Category(
        "streaming_content",
        "no",
        "none",
        "Licensed content, playback rights, and streaming UX are service-bound.",
    ),
    "hardware_device": Category(
        "hardware_device",
        "no",
        "none",
        "Drivers, peripherals, and device-specific control need native integrations.",
    ),
    "password_identity_security": Category(
        "password_identity_security",
        "no",
        "none",
        "Secrets, MFA, encryption, and autofill have a stricter trust model than a coding-agent skill.",
    ),
    "creative_pro_editor": Category(
        "creative_pro_editor",
        "partial",
        "image-batch-convert / candidate video-batch-utility",
        "Agents can automate prep/export/metadata, but not replace the real-time canvas or timeline.",
    ),
    "music_audio_pro": Category(
        "music_audio_pro",
        "partial",
        "candidate audio-metadata-audit",
        "Metadata, conversion, and filing fit skills; instruments, notation, and DAW workflows stay as apps.",
    ),
    "notes_tasks_writing_app": Category(
        "notes_tasks_writing_app",
        "partial",
        "documents / writing workflows",
        "Agents can draft, summarize, migrate, and clean content; persistent UI state remains the app value.",
    ),
    "education_exam_service": Category(
        "education_exam_service",
        "no",
        "none",
        "Exam delivery, identity, and course/service content are not local replacement targets.",
    ),
    "remote_desktop_virtualization": Category(
        "remote_desktop_virtualization",
        "no",
        "none",
        "VMs and remote desktop need live native clients and OS/network integration.",
    ),
    "shopping_service": Category(
        "shopping_service",
        "no",
        "none",
        "Retail/account/extension service, not a local deterministic workflow.",
    ),
    "screenshot_ocr_capture": Category(
        "screenshot_ocr_capture",
        "partial",
        "screenshot-organizer / candidate ocr-capture-tool",
        "Organization, extraction, and reports fit skills; hotkey capture/annotation UX usually remains resident.",
    ),
    "transcription_audio_notes": Category(
        "transcription_audio_notes",
        "partial",
        "candidate audio-transcript-summary",
        "Transcription and summaries fit agents; live recorder UX and permissions remain app-specific.",
    ),
    "presentation_screen_tools": Category(
        "presentation_screen_tools",
        "partial",
        "presentations / screenshot-organizer",
        "Deck/content generation fits skills; live annotation, remotes, and screen overlays need resident tools.",
    ),
    "file_manager_transfer": Category(
        "file_manager_transfer",
        "partial",
        "mac-app-inventory / backup-audit / shell scripts",
        "Inventory and batch file operations fit skills; device/network transfer clients may still be needed.",
    ),
    "genealogy_reference": Category(
        "genealogy_reference",
        "partial",
        "candidate structured-data-report",
        "Import/export/report generation can be agentic; domain database UI remains app-specific.",
    ),
    "web_download_archive": Category(
        "web_download_archive",
        "partial",
        "playwright / candidate web-archive-tool",
        "Download/export workflows can be automated; browser/session behavior still matters.",
    ),
    "timer_focus_utility": Category(
        "timer_focus_utility",
        "partial",
        "candidate focus-timer-config",
        "Reports and simple timers can be scripted; always-on focus/reminder UX remains an app.",
    ),
    "diagram_mindmap": Category(
        "diagram_mindmap",
        "partial",
        "excalidraw-diagram / presentations",
        "Agents can generate diagrams and plans; manual canvas editing remains app value.",
    ),
    "clipboard_automation": Category(
        "clipboard_automation",
        "partial",
        "candidate clipboard-audit-tool",
        "Audits and simple transforms fit scripts; live clipboard history needs a resident utility.",
    ),
    "data_visualization_or_analysis": Category(
        "data_visualization_or_analysis",
        "partial",
        "spreadsheets / csv-clean-room",
        "One-off analysis and generated charts fit skills; resident UI remains optional.",
    ),
    "unknown_or_low_signal": Category(
        "unknown_or_low_signal",
        "unknown",
        "manual review",
        "Parsed chart row lacks enough product signal for a defensible replacement call.",
    ),
}


READINESS_BY_CATEGORY = {
    "ai_chat_or_writing": AgentReadiness(
        "native_agent_surface",
        "The product category is already an AI/chat/writing surface; agent substitution depends on account-specific features.",
        "category_inference",
    ),
    "archive_tools": AgentReadiness(
        "scriptable_cli",
        "Core actions map to system or open-source archive commands and this repo's archive skill.",
        "repo_skill",
    ),
    "backup_sync_storage_service": AgentReadiness(
        "scriptable_cli",
        "Backup status and inventory can be inspected by local CLI tools; sync engines remain app/service-owned.",
        "repo_skill",
    ),
    "browser_extension_or_web_wrapper": AgentReadiness(
        "web_automation",
        "Many rows are browser wrappers/extensions that can be replaced or assisted by browser automation, shortcuts, or service APIs.",
        "category_inference",
    ),
    "clipboard_automation": AgentReadiness(
        "scriptable_cli",
        "Simple clipboard transforms can be scripted; persistent clipboard history needs a resident utility.",
        "category_inference",
    ),
    "creative_pro_editor": AgentReadiness(
        "partial_file_automation",
        "Files and exports are automatable; the live creative canvas/timeline is not agent-native.",
        "category_inference",
    ),
    "data_visualization_or_analysis": AgentReadiness(
        "native_agent_surface",
        "One-off analysis and generated tables/charts map directly to agent spreadsheet/data workflows.",
        "repo_skill",
    ),
    "developer_tools": AgentReadiness(
        "native_agent_surface",
        "Developer workflows commonly expose CLIs, APIs, local files, and MCP-ready repo context.",
        "mcp_reference",
    ),
    "diagram_mindmap": AgentReadiness(
        "partial_file_automation",
        "Agents can generate diagram artifacts; manual canvas interaction remains app-specific.",
        "category_inference",
    ),
    "education_exam_service": AgentReadiness(
        "not_a_fit",
        "Exam delivery and identity workflows should not be replaced by agent automation.",
        "category_inference",
    ),
    "email_calendar_meetings": AgentReadiness(
        "api_or_connector_ready",
        "Email/calendar/meeting systems commonly expose APIs or connectors for search, drafting, summaries, and scheduling.",
        "mcp_reference",
    ),
    "file_manager_transfer": AgentReadiness(
        "scriptable_cli",
        "Many transfer and file-management flows can be handled by shell tools, rsync-like workflows, or provider APIs.",
        "category_inference",
    ),
    "genealogy_reference": AgentReadiness(
        "partial_file_automation",
        "Imports, exports, and reports can be generated if data files are accessible; the domain database UI remains app-specific.",
        "category_inference",
    ),
    "hardware_device": AgentReadiness(
        "not_a_fit",
        "Drivers and hardware control require vendor/native integrations.",
        "category_inference",
    ),
    "image_media_batch": AgentReadiness(
        "scriptable_cli",
        "Batch image conversion, metadata, and duplicate scans are CLI/file-workflow friendly.",
        "repo_skill",
    ),
    "messaging_social": AgentReadiness(
        "low",
        "Messaging APIs may exist, but personal encrypted/push UX and network effects are not agent-replacement targets.",
        "category_inference",
    ),
    "music_audio_pro": AgentReadiness(
        "partial_file_automation",
        "Metadata, conversion, and filing are automatable; DAW/instrument/notation interaction remains app-specific.",
        "category_inference",
    ),
    "network_security": AgentReadiness(
        "not_a_fit",
        "VPN/proxy/MFA tools have OS networking and trust boundaries that should not be replaced by ad hoc agent code.",
        "category_inference",
    ),
    "notes_tasks_writing_app": AgentReadiness(
        "api_or_connector_ready",
        "Drafting, summarization, and migration are agent-friendly; persistent app state may require APIs or export formats.",
        "category_inference",
    ),
    "office_documents": AgentReadiness(
        "api_or_connector_ready",
        "Document/spreadsheet/presentation generation and conversion are supported by agent file workflows and provider APIs.",
        "repo_skill",
    ),
    "password_identity_security": AgentReadiness(
        "not_a_fit",
        "Secret storage, autofill, encryption, and MFA are the wrong trust model for coding-agent replacement.",
        "category_inference",
    ),
    "pdf_document_tools": AgentReadiness(
        "scriptable_cli",
        "Batch PDF inspection and manipulation can use local libraries/tools; visual signing/editing remains app-specific.",
        "repo_skill",
    ),
    "presentation_screen_tools": AgentReadiness(
        "partial_file_automation",
        "Deck generation is agent-friendly; live overlays, remotes, and screen controls need resident utilities.",
        "category_inference",
    ),
    "remote_desktop_virtualization": AgentReadiness(
        "not_a_fit",
        "VMs and remote desktop clients require native live session and OS/network integration.",
        "category_inference",
    ),
    "screenshot_ocr_capture": AgentReadiness(
        "scriptable_cli",
        "Post-capture organization and OCR can be automated; capture hotkeys and overlays remain resident behavior.",
        "repo_skill",
    ),
    "shopping_service": AgentReadiness(
        "low",
        "Retail/account extension behavior is service-bound and not a local replacement target.",
        "category_inference",
    ),
    "storage_audit": AgentReadiness(
        "scriptable_cli",
        "Disk inspection maps to local CLI probes and this repo's storage audit skill.",
        "repo_skill",
    ),
    "streaming_content": AgentReadiness(
        "not_a_fit",
        "Licensed content, DRM, and playback UX are service-bound.",
        "category_inference",
    ),
    "system_utility": AgentReadiness(
        "partial_file_automation",
        "Inspection/config generation can be automated; always-on menu-bar/input behavior usually needs an app.",
        "category_inference",
    ),
    "timer_focus_utility": AgentReadiness(
        "partial_file_automation",
        "Simple timers and reports are scriptable; reminders and always-on focus behavior remain resident utilities.",
        "category_inference",
    ),
    "transcription_audio_notes": AgentReadiness(
        "native_agent_surface",
        "Transcription and summarization are native agent/LLM workflows when audio files are accessible.",
        "category_inference",
    ),
    "unknown_or_low_signal": AgentReadiness(
        "unknown",
        "Insufficient product signal in the parsed chart row.",
        "manual_review",
    ),
    "video_media_batch": AgentReadiness(
        "scriptable_cli",
        "ffmpeg-style transcode, trim, metadata, and caption workflows are CLI/file-workflow friendly.",
        "category_inference",
    ),
    "web_download_archive": AgentReadiness(
        "web_automation",
        "Browser automation and scripted download/export flows can handle much of the job.",
        "category_inference",
    ),
    "window_workspace_management": AgentReadiness(
        "low",
        "Core value is resident accessibility/input/window behavior rather than an agent callable workflow.",
        "category_inference",
    ),
}


READINESS_BY_APP = {
    "Notion Web Clipper": AgentReadiness(
        "native_mcp",
        "Notion has an official hosted MCP server for agents; the web clipper itself is still an extension.",
        "official_notion_mcp",
    ),
    "Canva: AI Video & Photo Editor": AgentReadiness(
        "native_mcp",
        "Canva has an official MCP setup path for AI tools; the visual design canvas still remains Canva.",
        "official_canva_mcp",
    ),
    "GitHub": AgentReadiness(
        "native_mcp",
        "GitHub has an official MCP server for repo, issue, PR, and workflow automation.",
        "official_github_mcp",
    ),
    "Slack for Desktop": AgentReadiness(
        "api_or_connector_ready",
        "Slack has mature developer APIs, CLI/docs surfaces, and LLM-friendly docs; live chat remains the app.",
        "official_slack_api",
    ),
    "Telegram": AgentReadiness(
        "api_or_connector_ready",
        "Telegram exposes Bot APIs and webhooks, but the personal encrypted chat client is not replaced.",
        "official_telegram_bot_api",
    ),
    "Tailscale": AgentReadiness(
        "scriptable_cli",
        "Tailscale exposes a documented CLI; the VPN client and trust boundary remain native.",
        "official_tailscale_cli",
    ),
    "UTM Virtual Machines": AgentReadiness(
        "scriptable_cli",
        "UTM is open source and exposes command/control surfaces, but live VM sessions remain native.",
        "official_utm_repo",
    ),
    "Cyberduck": AgentReadiness(
        "scriptable_cli",
        "Cyberduck has the official `duck` CLI for scripted transfer workflows.",
        "official_cyberduck_cli",
    ),
    "MediaInfo": AgentReadiness(
        "scriptable_cli",
        "MediaInfo has a CLI and library-backed metadata workflow.",
        "official_mediainfo_cli",
    ),
    "LosslessCut": AgentReadiness(
        "scriptable_cli",
        "LosslessCut is open source and has CLI/API surfaces for basic automation.",
        "official_losslesscut_repo",
    ),
    "Things 3": AgentReadiness(
        "api_or_connector_ready",
        "Things supports URL scheme and x-callback automation; persistent task UI remains the app.",
        "official_things_url_scheme",
    ),
    "iA Writer": AgentReadiness(
        "api_or_connector_ready",
        "iA Writer supports Apple Shortcuts and URL commands; writing workflow remains file/app based.",
        "official_ia_writer_shortcuts",
    ),
    "Due - Reminders & Timers": AgentReadiness(
        "api_or_connector_ready",
        "Due documents a URL scheme and x-callback automation surface.",
        "official_due_url_scheme",
    ),
    "Linear": AgentReadiness(
        "native_mcp",
        "Linear has an official remote MCP server with Codex and Claude setup instructions.",
        "official_linear_mcp",
    ),
    "Microsoft Word": AgentReadiness(
        "api_or_connector_ready",
        "Office documents can be generated and edited through file workflows and Microsoft Graph/Office automation.",
        "category_inference",
    ),
    "Microsoft Excel": AgentReadiness(
        "api_or_connector_ready",
        "Spreadsheets can be generated and transformed through file workflows and Microsoft/Google APIs.",
        "category_inference",
    ),
    "Microsoft PowerPoint": AgentReadiness(
        "api_or_connector_ready",
        "Decks can be generated and transformed through file workflows and Microsoft/Google APIs.",
        "category_inference",
    ),
    "Microsoft Outlook": AgentReadiness(
        "api_or_connector_ready",
        "Mail and calendar workflows can be automated through Microsoft Graph-style APIs/connectors.",
        "category_inference",
    ),
    "Microsoft OneNote": AgentReadiness(
        "api_or_connector_ready",
        "OneNote exposes Microsoft Graph APIs for notebook/page workflows; the canvas UI remains native.",
        "official_microsoft_graph",
    ),
    "OneDrive": AgentReadiness(
        "api_or_connector_ready",
        "Cloud file inventory and transfer can be handled through provider APIs; sync remains the native client.",
        "category_inference",
    ),
    "Xcode": AgentReadiness(
        "scriptable_cli",
        "Xcode exposes developer CLI workflows such as builds and developer cache paths; the IDE remains native.",
        "category_inference",
    ),
    "Apple Developer": AgentReadiness(
        "api_or_connector_ready",
        "Apple developer workflows expose App Store Connect APIs, but portal/account actions remain specialized.",
        "apple_app_store_connect_api",
    ),
    "TestFlight": AgentReadiness(
        "api_or_connector_ready",
        "TestFlight is reachable through App Store Connect workflows; the distribution service itself remains Apple-owned.",
        "apple_app_store_connect_api",
    ),
}


EXACT_CATEGORY = {
    "WhatsApp Messenger": "messaging_social",
    "Telegram": "messaging_social",
    "WeChat": "messaging_social",
    "App for Facebook Messenger": "messaging_social",
    "App for TikTok": "messaging_social",
    "ChatShare for WhatsApp": "messaging_social",
    "App For Team Meetings": "email_calendar_meetings",
    "Amazon Prime Video": "streaming_content",
    "Amazon Kindle: Reading App": "streaming_content",
    "TV Launcher - Live UK Channels": "streaming_content",
    "IPTV Smart Pro - 4K Live TV": "streaming_content",
    "Streaming for Netflix": "streaming_content",
    "Streaming Player for Peacock": "streaming_content",
    "Teleparty - Watch TV Together": "streaming_content",
    "Friendly Streaming Browser": "streaming_content",
    "Streaming Master": "streaming_content",
    "NordVPN: VPN Fast & Secure": "network_security",
    "VPN: Super Unlimited, Fast VPN": "network_security",
    "ExpressVPN · Secure & Fast VPN": "network_security",
    "Happ - Proxy Utility": "network_security",
    "Free VPN by Free VPN .org™": "network_security",
    "VPN cat: Fast Secure Unlimited": "network_security",
    "VPN Proxy Maste® Unlimited VPN": "network_security",
    "Tailscale": "network_security",
    "Surfshark VPN: stable & fast": "network_security",
    "WireGuard": "network_security",
    "Shadowrocket": "network_security",
    "Quantumult X": "network_security",
    "Dynamic DNS client - RealDNS": "network_security",
    "IP Scanner Ultra": "network_security",
    "Microsoft Word": "office_documents",
    "Microsoft Excel": "office_documents",
    "Microsoft PowerPoint": "office_documents",
    "WPS Office: AI Doc, PDF, Sheet": "office_documents",
    "LibreOffice": "office_documents",
    "Spreadsheet-xlsx&csv editor": "office_documents",
    "Docs for Google Docs and Drive": "office_documents",
    "Microsoft Outlook": "email_calendar_meetings",
    "Slack for Desktop": "email_calendar_meetings",
    "Join for Zoom Meetings": "email_calendar_meetings",
    "Mail for Gmail": "email_calendar_meetings",
    "Join for Teams": "email_calendar_meetings",
    "Mail+ for Gmail": "email_calendar_meetings",
    "Calendar for Google Calendar‎": "email_calendar_meetings",
    "Join for Zoom": "email_calendar_meetings",
    "App for Zoom Meetings °": "email_calendar_meetings",
    "Meeting for Teams ®": "email_calendar_meetings",
    "Webmail App": "email_calendar_meetings",
    "GCal for Google Calendar": "email_calendar_meetings",
    "PST Viewer - Email Reader": "email_calendar_meetings",
    "Unibox": "email_calendar_meetings",
    "MailRaider": "email_calendar_meetings",
    "MailTrackerBlocker for Mail": "browser_extension_or_web_wrapper",
    "Microsoft Copilot": "ai_chat_or_writing",
    "AI ChatbotㆍAsk AI Anything 5.4": "ai_chat_or_writing",
    "C.AI: AI Chatbot Assistant": "ai_chat_or_writing",
    "AI Chatbot - Ask AI Anything‎": "ai_chat_or_writing",
    "Chatbot: Ask Chat AI Assistant": "ai_chat_or_writing",
    "Grammarly: AI Writing App": "ai_chat_or_writing",
    "Collective AI": "ai_chat_or_writing",
    "Xcode": "developer_tools",
    "TestFlight": "developer_tools",
    "Apple Developer": "developer_tools",
    "Icon Composer": "developer_tools",
    "Node.js/JavaScript Compiler": "developer_tools",
    "App Trust Preview": "password_identity_security",
    "HP: Print and Support": "hardware_device",
    "Brother iPrint&Scan": "hardware_device",
    "Apple Configurator": "hardware_device",
    "HP Smart Printer App & Scanner": "hardware_device",
    "Shutter Counter": "hardware_device",
    "ShutterCount": "hardware_device",
    "Webcam Settings": "hardware_device",
    "OneDrive": "backup_sync_storage_service",
    "Parachute Backup": "backup_sync_storage_service",
    "Offline Files": "backup_sync_storage_service",
    "FileBrowser Pro": "file_manager_transfer",
    "Instashare - Transfer files": "file_manager_transfer",
    "MacDroid - Manager for Android": "file_manager_transfer",
    "LinkMyDroid": "file_manager_transfer",
    "Windows App": "remote_desktop_virtualization",
    "UTM Virtual Machines": "remote_desktop_virtualization",
    "Parallels Desktop": "remote_desktop_virtualization",
    "Jump Desktop (RDP, VNC, Fluid)": "remote_desktop_virtualization",
    "Capital One Shopping Extension": "shopping_service",
    "Okta Verify": "password_identity_security",
    "pwSafe - Password Safe": "password_identity_security",
    "Password Manager Data Vault": "password_identity_security",
    "Paranoia File Encryption PRO": "password_identity_security",
    "eWallet": "password_identity_security",
    "CleanMyMac": "storage_audit",
    "DaisyDisk": "storage_audit",
    "GrandPerspective": "storage_audit",
    "Disk Drill Data Recovery": "storage_audit",
    "The Unarchiver": "archive_tools",
    "Unzip - RAR ZIP 7Z Unarchiver": "archive_tools",
    "RAR Extractor - Unarchiver Pro": "archive_tools",
    "Keka": "archive_tools",
    "PDFgear: PDF Editor & Reader": "pdf_document_tools",
    "PDF Reader: PDF Editor,Convert": "pdf_document_tools",
    "PDF Expert - Edit, Sign PDFs": "pdf_document_tools",
    "PDF Reader Pro - Edit&Convert": "pdf_document_tools",
    "Basic PDF Reader": "pdf_document_tools",
    "Create Booklet 2": "pdf_document_tools",
    "PDF Professional Suite": "pdf_document_tools",
    "PDF Merge & Split - PageForge": "pdf_document_tools",
    "PDFScanner - Scanning and OCR": "pdf_document_tools",
    "PDF Toolkit +": "pdf_document_tools",
    "PDF to Word +": "pdf_document_tools",
    "Redacto": "pdf_document_tools",
    "Adobe Lightroom: Photo Editor": "creative_pro_editor",
    "Pixelmator Pro": "creative_pro_editor",
    "Pixelmator Pro: Edit Images": "creative_pro_editor",
    "PixelStyle Photo Editor": "image_media_batch",
    "PhotoSweeper": "image_media_batch",
    "Iris: Photo & Video Library": "image_media_batch",
    "Logoist 6 - Graphic Design": "creative_pro_editor",
    "Upscayl": "image_media_batch",
    "Starry Landscape Stacker": "image_media_batch",
    "Phiewer PRO": "image_media_batch",
    "GraphicConverter 12": "image_media_batch",
    "Sketchbook Pro": "creative_pro_editor",
    "CapCut: Photo & Video Editor": "video_media_batch",
    "DaVinci Resolve": "creative_pro_editor",
    "Final Cut Pro: Create Video": "creative_pro_editor",
    "Final Cut Pro": "creative_pro_editor",
    "LosslessCut": "video_media_batch",
    "BRAW Toolbox": "video_media_batch",
    "Gyroflow Toolbox": "video_media_batch",
    "3D Video Meta Data injector": "video_media_batch",
    "Motion": "creative_pro_editor",
    "MKPlayer - MKV & Media Player": "video_media_batch",
    "captionTranslator": "video_media_batch",
    "Logic Pro": "music_audio_pro",
    "Logic Pro: Make Music": "music_audio_pro",
    "MainStage": "music_audio_pro",
    "Minimoog Model D Synthesizer": "music_audio_pro",
    "forScore": "music_audio_pro",
    "Silicio: Widgets + Mini Player": "music_audio_pro",
    "VinylPod - Music Widget": "music_audio_pro",
    "djay - DJ App & AI Mixer": "music_audio_pro",
    "Mp3tag": "music_audio_pro",
    "Tune Sweeper": "music_audio_pro",
    "Patterning 3: Drum Machine": "music_audio_pro",
    "Meta - Music Tag Editor": "music_audio_pro",
    "miRack": "music_audio_pro",
    "iReal Pro": "music_audio_pro",
    "Goodnotes: AI Notes, Docs, PDF": "notes_tasks_writing_app",
    "Microsoft OneNote": "notes_tasks_writing_app",
    "Notability: AI Notes & PDF app": "notes_tasks_writing_app",
    "Things 3": "notes_tasks_writing_app",
    "Scrivener 3": "notes_tasks_writing_app",
    "iA Writer": "notes_tasks_writing_app",
    "Final Draft 13": "notes_tasks_writing_app",
    "md - Markdown writing App": "notes_tasks_writing_app",
    "Quiver - take better notes": "notes_tasks_writing_app",
    "GoodTask": "notes_tasks_writing_app",
    "ReminderBridge": "notes_tasks_writing_app",
    "TaskControl for Asana": "notes_tasks_writing_app",
    "Narrativ Timeline": "notes_tasks_writing_app",
    "Scrap Paper": "notes_tasks_writing_app",
    "SideNotes & Workspaces": "notes_tasks_writing_app",
    "PlainPad": "notes_tasks_writing_app",
    "Scratchpad": "notes_tasks_writing_app",
    "Outliner": "notes_tasks_writing_app",
    "Byword": "notes_tasks_writing_app",
    "OmmWriter": "notes_tasks_writing_app",
    "WriteRoom": "notes_tasks_writing_app",
    "iWriter 2": "notes_tasks_writing_app",
    "To-do Lists": "notes_tasks_writing_app",
    "Due - Reminders & Timers": "timer_focus_utility",
    "Bluebook Exams": "education_exam_service",
    "Focus & ADHD Reading - Glide": "education_exam_service",
    "Save to Pinterest": "browser_extension_or_web_wrapper",
    "App for Youtube!": "browser_extension_or_web_wrapper",
    "Open Link Pro - Browser Picker": "browser_extension_or_web_wrapper",
    "uBlock Origin Lite": "browser_extension_or_web_wrapper",
    "App for YouTube ℠": "browser_extension_or_web_wrapper",
    "App for Google Search ®‎": "browser_extension_or_web_wrapper",
    "App for YouTube •": "browser_extension_or_web_wrapper",
    "Openly a Link - Browser Picker": "browser_extension_or_web_wrapper",
    "Open App for All Browser": "browser_extension_or_web_wrapper",
    "App for Gmail ®": "email_calendar_meetings",
    "Notion Web Clipper": "browser_extension_or_web_wrapper",
    "Wipr 2": "browser_extension_or_web_wrapper",
    "SponsorBlock for Safari": "browser_extension_or_web_wrapper",
    "Vinegar - Tube Cleaner": "browser_extension_or_web_wrapper",
    "SiteSucker": "web_download_archive",
    "Dark Night - mode for Safari": "browser_extension_or_web_wrapper",
    "Noir - Dark Mode for Safari": "browser_extension_or_web_wrapper",
    "Dark Reader for Safari": "browser_extension_or_web_wrapper",
    "Tampermonkey": "browser_extension_or_web_wrapper",
    "Tampermonkey Classic": "browser_extension_or_web_wrapper",
    "xSearch for Safari": "browser_extension_or_web_wrapper",
    "MarkDownload": "web_download_archive",
    "AI Overview Hider for Google": "browser_extension_or_web_wrapper",
    "UnTrap for YouTube": "browser_extension_or_web_wrapper",
    "TabPilot": "browser_extension_or_web_wrapper",
    "Ad Auto-Skipper for YouTube": "browser_extension_or_web_wrapper",
    "Velja": "browser_extension_or_web_wrapper",
    "WidgetWall": "system_utility",
    "Color Widgets": "system_utility",
    "Widgetter - Custom Desktop": "system_utility",
    "Amphetamine": "system_utility",
    "NotchBox - Easier Drag & Drop": "window_workspace_management",
    "iWallpaper - Live Wallpaper": "system_utility",
    "OP Auto Clicker": "system_utility",
    "DeskMat - Cover your Desktop": "system_utility",
    "BetterSnapTool": "window_workspace_management",
    "Magnet": "window_workspace_management",
    "Moom Classic": "window_workspace_management",
    "Command X": "system_utility",
    "Smart Converter Pro 3": "video_media_batch",
    "Screen Shade": "system_utility",
    "Color Folder Master": "system_utility",
    "Mouse Coordinates": "system_utility",
    "AirSpace: Manage Desktop Spaces": "window_workspace_management",
    "MenuBarPad": "notes_tasks_writing_app",
    "Inset: Preview Any Screen Area": "presentation_screen_tools",
    "Paperman: Your screen as paper": "system_utility",
    "Klack": "system_utility",
    "iStat Menus 7": "system_utility",
    "Folder Tidy": "file_manager_transfer",
    "AltTab Switcher": "window_workspace_management",
    "HazeOver - Distraction Dimmer": "system_utility",
    "NotchPrompter": "system_utility",
    "nvEnvy": "unknown_or_low_signal",
    "Maccy": "clipboard_automation",
    "Unclutter": "notes_tasks_writing_app",
    "Hide Mouse Cursor": "system_utility",
    "Glance - Prevent Eye Strain": "system_utility",
    "Count Down: Menu Bar Timer": "timer_focus_utility",
    "Histogrammer": "data_visualization_or_analysis",
    "Quit All Apps": "system_utility",
    "FolderToList": "file_manager_transfer",
    "Day Progress": "timer_focus_utility",
    "PreviewMarkdown": "notes_tasks_writing_app",
    "Show StopWatch": "timer_focus_utility",
    "CCCCorners": "window_workspace_management",
    "CopyClip 2 - Clipboard Manager": "clipboard_automation",
    "Cursor Pro": "screenshot_ocr_capture",
    "Theine": "system_utility",
    "Timeless: Alarm Clock": "timer_focus_utility",
    "Gestimer 2": "timer_focus_utility",
    "Lock Pro": "password_identity_security",
    "Be Focused Pro: Pomodoro Timer": "timer_focus_utility",
    "Gestimer (Legacy)": "timer_focus_utility",
    "The Clock": "timer_focus_utility",
    "Split Screen": "window_workspace_management",
    "Canva: AI Video & Photo Editor": "creative_pro_editor",
    "MediaInfo": "video_media_batch",
    "TextSniper": "screenshot_ocr_capture",
    "Greenshot": "screenshot_ocr_capture",
    "Presentify - Screen Annotation": "presentation_screen_tools",
    "FinalShot Screenshot Capture": "screenshot_ocr_capture",
    "Whisper Notes - Speech to Text": "transcription_audio_notes",
    "Trace: On-Device Transcripts": "transcription_audio_notes",
    "Aiko": "transcription_audio_notes",
    "AudioNote-Note+Voice Recorder": "transcription_audio_notes",
    "eXtra Voice Recorder Pro.": "transcription_audio_notes",
    "Clicker - Presentation Remote": "presentation_screen_tools",
    "SimpleMind Pro": "diagram_mindmap",
    "TouchDraw 2: Draw and Diagram": "diagram_mindmap",
    "Scapple": "diagram_mindmap",
    "iCircuit": "diagram_mindmap",
    "Project Planner - Gantt app": "diagram_mindmap",
    "RailModeller Pro": "diagram_mindmap",
    "MacFamilyTree 11": "genealogy_reference",
    "Short Run": "system_utility",
    "Parall": "system_utility",
    "nvEnvy": "notes_tasks_writing_app",
    "iA Presenter": "presentation_screen_tools",
    "Cyberduck": "file_manager_transfer",
    "DuckDuckGo, optional Duck.ai": "browser_extension_or_web_wrapper",
    "Apps for Google App": "browser_extension_or_web_wrapper",
    "Openly a Link - Browser Picker": "browser_extension_or_web_wrapper",
}


def classify(name: str) -> Category:
    key = EXACT_CATEGORY.get(name)
    if key:
        return CATEGORY_META[key]
    lowered = name.lower()
    for needle, category in [
        ("vpn", "network_security"),
        ("pdf", "pdf_document_tools"),
        ("gmail", "email_calendar_meetings"),
        ("calendar", "email_calendar_meetings"),
        ("youtube", "browser_extension_or_web_wrapper"),
        ("safari", "browser_extension_or_web_wrapper"),
        ("browser", "browser_extension_or_web_wrapper"),
        ("chatbot", "ai_chat_or_writing"),
        ("ai ", "ai_chat_or_writing"),
        ("widget", "system_utility"),
        ("clipboard", "clipboard_automation"),
        ("markdown", "notes_tasks_writing_app"),
        ("timer", "timer_focus_utility"),
        ("recorder", "transcription_audio_notes"),
        ("screen", "presentation_screen_tools"),
        ("converter", "video_media_batch"),
    ]:
        if needle in lowered:
            return CATEGORY_META[category]
    return CATEGORY_META["unknown_or_low_signal"]


def readiness_for(name: str, category_label: str) -> AgentReadiness:
    return READINESS_BY_APP.get(name, READINESS_BY_CATEGORY[category_label])


def row(chart: str, rank: int, name: str, price: str, store_category: str) -> dict[str, str | int]:
    category = classify(name)
    readiness = readiness_for(name, category.label)
    return {
        "chart": chart,
        "rank": rank,
        "name": name,
        "price": price,
        "store_category": store_category,
        "mapped_category": category.label,
        "replaceability": category.replaceability,
        "skill_or_tool_fit": category.skill_fit,
        "reason": category.reason,
        "ai_agent_readiness": readiness.level,
        "ai_agent_readiness_basis": readiness.basis,
        "ai_agent_readiness_evidence_key": readiness.evidence_key,
    }


def build_rows() -> dict[str, list[dict[str, str | int]]]:
    paid_price_by_name = {name: price for _, name, price in PAID_OVERALL_TOP}
    return {
        "free_overall": [
            row("free_overall", rank, name, price, store_category)
            for rank, name, price, store_category in FREE_TOP
        ],
        "paid_overall": [
            row("paid_overall", rank, name, price, "Paid Overall")
            for rank, name, price in PAID_OVERALL_TOP
        ],
        "paid_productivity": [
            row(
                "paid_productivity",
                rank,
                name,
                PRODUCTIVITY_PRICE_OVERRIDES.get(name, paid_price_by_name.get(name, "not captured")),
                "Productivity",
            )
            for rank, name in PAID_PRODUCTIVITY_TOP
        ],
    }


def write_json(rows_by_chart: dict[str, list[dict[str, str | int]]]) -> None:
    output = {
        "captured_at": "2026-06-24T17:00:00+01:00",
        "source_notes": [
            "Free chart rows use the parsed local Mac free chart feed; Apple returned 98 rows for the requested top 100.",
            "Paid overall and paid Productivity chart rows use Val's local Mac App Store screenshots and the existing OCR-assisted transcription.",
            "Paid overall prices are the visible screenshot prices; Open/Open-Purchased means the account already had that app so the storefront price was hidden.",
            "Paid Productivity prices are filled from overlapping paid-overall rows and local screenshot price checks; Open/View means the storefront hid the price behind the account state.",
            "Mapped categories describe the job-to-be-done, not only Apple's storefront category.",
        ],
        "category_definitions": {
            key: {
                "replaceability": value.replaceability,
                "skill_or_tool_fit": value.skill_fit,
                "reason": value.reason,
            }
            for key, value in sorted(CATEGORY_META.items())
        },
        "ai_agent_readiness_definitions": {
            "native_mcp": "Official app/vendor MCP server exists.",
            "native_agent_surface": "The product category is already an AI/agent-native workflow or maps directly to agent execution.",
            "api_or_connector_ready": "Official API, connector, or provider automation surface exists, but not necessarily app-specific MCP.",
            "scriptable_cli": "Core workflow is accessible through local CLI tools, libraries, or generated scripts.",
            "web_automation": "Workflow can be automated through browser automation or service web UI, with session/ToS caveats.",
            "partial_file_automation": "Files/exports/config can be automated; core live UI remains app-specific.",
            "low": "Some automation may exist, but the core job is not a good agent replacement target.",
            "not_a_fit": "Trust, OS integration, hardware, DRM, or real-time service behavior makes agent replacement inappropriate.",
            "unknown": "Insufficient product signal.",
        },
        "charts": rows_by_chart,
    }
    target = DATA_DIR / "top-mac-app-category-mapping-2026-06-24.json"
    target.write_text(json.dumps(output, indent=2, ensure_ascii=False) + "\n")


def write_paid_source_json(rows_by_chart: dict[str, list[dict[str, str | int]]]) -> None:
    paid_overall = [
        {"rank": item["rank"], "name": item["name"], "price": item["price"]}
        for item in rows_by_chart["paid_overall"]
    ]
    paid_productivity = [
        {"rank": item["rank"], "name": item["name"], "price": item["price"]}
        for item in rows_by_chart["paid_productivity"]
    ]
    output = {
        "captured_at": "2026-06-24T17:00:00+01:00",
        "source": "Mac App Store UI screenshots captured by Val on macOS",
        "apple_web_chart_urls": {
            "overall": "https://apps.apple.com/us/mac/charts/36?chart=top-paid",
            "productivity": "https://apps.apple.com/us/mac/charts/6007?chart=top-paid",
        },
        "notes": [
            "Apple legacy RSS top paid Mac feed returned a valid but empty feed.",
            "The Mac App Store UI exposed the paid chart directly.",
            "This file is an OCR-assisted manual transcription from local screenshots, checked against the visible ranked rows.",
            "Raw screenshots are not committed to avoid repository bloat.",
            "Paid Productivity prices are captured from overlapping paid-overall rows and local screenshot price checks; Open/View means the storefront hid the price behind the account state.",
        ],
        "top_paid_mac_apps_overall": paid_overall,
        "top_paid_mac_productivity_apps": paid_productivity,
    }
    target = DATA_DIR / "top-paid-mac-apps-us-app-store-ui-2026-06-24.json"
    target.write_text(json.dumps(output, indent=2, ensure_ascii=False) + "\n")


def app_ref(item: dict[str, str | int]) -> str:
    return f"#{item['rank']} {item['name']} ({item['price']})"


def table_rows(items: list[dict[str, str | int]]) -> list[str]:
    lines = ["| Rank | App | Price | Store category | Mapped category | Core replaceability | AI-agent readiness | Skill/tool fit | Why |"]
    lines.append("|---:|---|---|---|---|---|---|---|---|")
    for item in items:
        lines.append(
            "| {rank} | {name} | {price} | {store_category} | {mapped_category} | "
            "{replaceability} | {ai_agent_readiness} | {skill_or_tool_fit} | {reason} |".format(**item)
        )
    return lines


def write_markdown(rows_by_chart: dict[str, list[dict[str, str | int]]]) -> None:
    grouped: dict[str, dict[str, list[dict[str, str | int]]]] = defaultdict(lambda: defaultdict(list))
    for chart, rows in rows_by_chart.items():
        for item in rows:
            grouped[str(item["mapped_category"])][chart].append(item)

    lines = [
        "# Top 100 App Category Mapping",
        "",
        "Snapshot date: 2026-06-24.",
        "",
        "This is the full row-level mapping, not examples. The free Mac chart returned 98 rows for the requested top 100; the paid overall and paid Productivity charts are mapped through rank 100.",
        "",
        "Source boundaries:",
        "",
        "- Free overall: parsed local Mac free chart feed.",
        "- Paid overall: Val's Mac App Store UI screenshots plus the existing OCR-assisted transcription.",
        "- Paid Productivity: Val's Mac App Store UI screenshots plus the existing OCR-assisted transcription.",
        "- `Open`, `Open/Purchased`, or `View` in the price column means the storefront hid the price behind the account state.",
        "",
        "Method:",
        "",
        "- Category means the app's job-to-be-done, not only Apple's App Store category.",
        "- `yes` means the core workflow can be handled by a skill/tool with transparent files and approval gates.",
        "- `partial` means an agent can replace batch/report/content workflows but not the live UI, account, service, or resident app behavior.",
        "- `no` means the app depends on a network, hardware, identity, real-time UI, or trust model that a coding-agent skill should not replace.",
        "- `unknown` means the parsed name did not carry enough product signal for a defensible replacement call.",
        "- AI-agent readiness is conservative: it records whether the app/category has a native MCP/agent surface, API/connector surface, CLI/script surface, browser automation path, partial file automation path, low readiness, or is not a fit.",
        "",
        "## Category Rollup",
        "",
        "| Mapped category | Free overall apps | Paid overall apps | Paid Productivity apps |",
        "|---|---|---|---|",
    ]

    for category in sorted(grouped):
        free = "<br>".join(app_ref(item) for item in grouped[category].get("free_overall", [])) or "-"
        paid = "<br>".join(app_ref(item) for item in grouped[category].get("paid_overall", [])) or "-"
        productivity = "<br>".join(app_ref(item) for item in grouped[category].get("paid_productivity", [])) or "-"
        lines.append(f"| {category} | {free} | {paid} | {productivity} |")

    lines.extend(["", "## Free Overall Top 98", ""])
    lines.extend(table_rows(rows_by_chart["free_overall"]))
    lines.extend(["", "## Paid Overall Top 100", ""])
    lines.extend(table_rows(rows_by_chart["paid_overall"]))
    lines.extend(["", "## Paid Productivity Top 100", ""])
    lines.extend(table_rows(rows_by_chart["paid_productivity"]))
    lines.append("")

    target = ROOT / "research" / "top-100-category-mapping.md"
    target.write_text("\n".join(lines))


def main() -> None:
    rows = build_rows()
    write_json(rows)
    write_paid_source_json(rows)
    write_markdown(rows)


if __name__ == "__main__":
    main()
